package hr.tvz.java.freelance.freelancemanagementtool.controller;

import hr.tvz.java.freelance.freelancemanagementtool.enums.ProjectStatus;
import hr.tvz.java.freelance.freelancemanagementtool.exception.DatabaseReadException;
import hr.tvz.java.freelance.freelancemanagementtool.model.Client;
import hr.tvz.java.freelance.freelancemanagementtool.model.Project;
import hr.tvz.java.freelance.freelancemanagementtool.repository.ClientDatabaseRepository;
import hr.tvz.java.freelance.freelancemanagementtool.repository.ProjectDatabaseRepository;
import javafx.collections.FXCollections;
import javafx.fxml.FXML;
import javafx.scene.control.*;
import javafx.stage.Stage;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.math.BigDecimal;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Controller for the project add/edit form.
 */
public class ProjectEditController {

    private static final Logger logger = LoggerFactory.getLogger(ProjectEditController.class);

    @FXML private TextField nameField;
    @FXML private TextArea descriptionArea;
    @FXML private ComboBox<Client> clientComboBox;
    @FXML private DatePicker startDatePicker;
    @FXML private DatePicker deadlinePicker;
    @FXML private TextField budgetField;
    @FXML private ComboBox<ProjectStatus> statusComboBox;

    private final ClientDatabaseRepository clientRepository = new ClientDatabaseRepository();
    private final ProjectDatabaseRepository projectRepository = new ProjectDatabaseRepository();

    private Project projectToEdit;

    /**
     * Initializes the controller, populating the choice boxes.
     */
    @FXML
    public void initialize() {
        statusComboBox.setItems(FXCollections.observableArrayList(ProjectStatus.values()));
        loadClients();
    }

    /**
     * Loads clients from the database and populates the client ComboBox.
     */
    private void loadClients() {
        try {
            List<Client> clients = clientRepository.findAll();
            clientComboBox.setItems(FXCollections.observableArrayList(clients));
        } catch (DatabaseReadException e) {
            logger.error("Failed to load clients for the form.", e);
            new Alert(Alert.AlertType.ERROR, "Could not load client data.").showAndWait();
        }
    }

    /**
     * Pre-populates the form fields with data from an existing project for editing.
     * @param project The project to be edited.
     */
    public void setProjectToEdit(Project project) {
        this.projectToEdit = project;
        nameField.setText(project.getName());
        descriptionArea.setText(project.getDescription());
        startDatePicker.setValue(project.getStartDate());
        deadlinePicker.setValue(project.getDeadline());
        budgetField.setText(project.getBudget().toPlainString());
        statusComboBox.setValue(project.getStatus());

        // Find and select the correct client in the ComboBox
        clientComboBox.getItems().stream()
                .filter(c -> c.getId() == project.getClientId())
                .findFirst()
                .ifPresent(clientComboBox::setValue);
    }

    /**
     * Handles the save button action. Validates input, confirms with the user,
     * and saves the project to the database.
     */
    @FXML
    private void handleSave() {
        // Basic validation
        if (nameField.getText().isBlank() || clientComboBox.getValue() == null || statusComboBox.getValue() == null || budgetField.getText().isBlank()) {
            new Alert(Alert.AlertType.WARNING, "Please fill in all required fields (Name, Client, Status, Budget).").show();
            return;
        }

        Alert confirmation = new Alert(Alert.AlertType.CONFIRMATION);
        confirmation.setTitle("Confirm Save");
        confirmation.setHeaderText("Are you sure you want to save these changes?");
        confirmation.setContentText("Project: " + nameField.getText());

        if (confirmation.showAndWait().orElse(ButtonType.CANCEL) == ButtonType.OK) {
            try {
                if (projectToEdit == null) { // This is a new project
                    Project newProject = new Project.Builder(0) // ID will be generated by DB
                            .withName(nameField.getText())
                            .withDescription(descriptionArea.getText())
                            .withClientId(clientComboBox.getValue().getId())
                            .withStartDate(startDatePicker.getValue())
                            .withDeadline(deadlinePicker.getValue())
                            .withBudget(new BigDecimal(budgetField.getText()))
                            .withStatus(statusComboBox.getValue())
                            .build();
                    projectRepository.save(newProject);
                    logger.info("User confirmed to save new project: {}", newProject.getName());
                } else { // This is an existing project
                    projectToEdit.setName(nameField.getText());
                    projectToEdit.setDescription(descriptionArea.getText());
                    projectToEdit.setClientId(clientComboBox.getValue().getId());
                    projectToEdit.setStartDate(startDatePicker.getValue());
                    projectToEdit.setDeadline(deadlinePicker.getValue());
                    projectToEdit.setBudget(new BigDecimal(budgetField.getText()));
                    projectToEdit.setStatus(statusComboBox.getValue());
                    projectRepository.update(projectToEdit);
                    logger.info("User confirmed to update project: {}", projectToEdit.getName());
                }
                closeWindow();
            } catch (NumberFormatException e) {
                logger.error("Invalid budget format entered.", e);
                new Alert(Alert.AlertType.ERROR, "Invalid format for Budget. Please enter a valid number.").show();
            }
        }
    }

    /**
     * Closes the form window.
     */
    @FXML
    private void handleCancel() {
        closeWindow();
    }

    private void closeWindow() {
        Stage stage = (Stage) nameField.getScene().getWindow();
        stage.close();
    }
}